script: bacon -q -Ilib -I. test/*_test.rb
before_install: bundle init --gemspec=ripl-multi_line.gemspec
rvm:
- ruby-head
- 2.0.0
- 1.9.3
- 1.9.2
- 1.8.7
# enable when jruby-19 + bacon bug resolved
# - jruby-19mode
- jruby-18mode
- rbx-19mode
